CURRENT_FORMAT_VERSION = 21
SUPPORTED_VERSIONS = (17, 18, 19, 20, 21)
faction_mapping = {
    0: 'DE',
    1: 'FR',
    2: 'IO',
    3: 'NX',
    4: 'PZ',
    5: 'SI',
    6: 'BW',
    7: 'SH',
    9: 'MT',
    10: 'BC',
    12: 'RU',
    'DE': 0,
    'FR': 1,
    'IO': 2,
    'NX': 3,
    'PZ': 4,
    'SI': 5,
    'BW': 6,
    'SH': 7,
    'MT': 9,
    'BC': 10,
    'RU': 12,
}
